### ISSUE TITLE
Something Wrong When i run this filter

### ISSUE THREAD

**Issue by TiantianZhang** [kuba-orlik/pandoc-dot2tex-filter#2]
I use this filter to draw figure with markdown and finally compile with xelatex. But, when i run the command, nothing happend.
my command is:
 pandoc test.md --filter=dot2tex-filter.py -H tikz-preamble.latex -o output.pdf --pdf-engine=xelatex

**Comment by kuba-orlik** [comment]
Which version of pandoc are you using?  This repo was written a few versions ago and maybe something has changed in the API since.

Also, it'd be great if you included a simple reproducible source file that demonstrates the issue :)

**Comment by TiantianZhang** [comment]
> Which version of pandoc are you using? This repo was written a few versions ago and maybe something has changed in the API since.
> 
> Also, it'd be great if you included a simple reproducible source file that demonstrates the issue :)
My pandoc version is pandoc 2.3.1 and python3.6. I just use the example in test.md. 
Which just as
```{.dot caption="example graph." label="the_example"}

graph graphname {
	 a [texlbl="$\alpha$"];
	 b [texlbl="$\beta$"];
	 b1 [texlbl="$\beta_1$"];
	 b2 [texlbl="$\beta_2$"];
     a -- b
     b -- b1
	 b -- b2
 }
```
My dot2tev version is based on pyhton3 at https://github.com/Naereen/dot2tex. And i test it, that is fine. So iam comfused about what wrong with my command line. when i enter it is just like nothing happend. Thanks very much for you reply.

**Comment by kuba-orlik** [comment]
What about the pandoc version? What's the output of

```
pandoc --version
```

?

**Comment by TiantianZhang** [comment]
My pandoc version is pandoc 2.3.1

**Comment by TiantianZhang** [comment]
> What about the pandoc version? What's the output of
> 
> ```
> pandoc --version
> ```
> ?


pandoc 2.3.1

**Comment by kuba-orlik** [comment]
Sorry for the late response. I assume the error you're seeing is because this plugin was written for an older version of Pandoc and there must've been some breaking API changes. I'd recommend trying this with an older version of Pandoc, especially 1.19 and 2.0 branches
